### ISSUE TITLE
fails to run on chromebook

### ISSUE THREAD

**Issue by darkoverlordofdata** [scalafx/scalafx-hello-world#11]
I get runtime errors trying this on my chromebook using linux:
Cant load AMD 64 bit .so on AARCH64 bit platform

Are there plans to add arm64 support?

**Comment by jpsacha** [comment]
To run on AARCH64 you will need JavaFX 17. SBT currently does not support using JavaFX 17. You will need to use Mill for build. You can find more discussion on that here: https://github.com/scalafx/scalafx/issues/362

**Comment by darkoverlordofdata** [comment]
Thanks for getting back on this. At this point that is too much pita ;) I'll stick with what is working out of the box (swing) to avoid deployment issues.
