### ISSUE TITLE
ClassNotFoundException in sbt run

### ISSUE THREAD

**Issue by phdoerfler** [scalafx/scalafx-hello-world#2]
Hi,

I have Java 8 installed and run into this issue:

```
git clone …
sbt run
```

> ```
> [info] Running hello.ScalaFXHelloWorld 
> [error] Exception in Application start method
> [error] Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
> [error]     at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:894)
> [error]     at com.sun.javafx.application.LauncherImpl.access$000(LauncherImpl.java:56)
> [error]     at com.sun.javafx.application.LauncherImpl$1.run(LauncherImpl.java:158)
> [error]     at java.lang.Thread.run(Thread.java:744)
> [error] Caused by: java.lang.NoClassDefFoundError: javafx/scene/chart/LineChart$SortingPolicy
> [error]     at scalafx.Includes$.<init>(Includes.scala:58)
> [error]     at scalafx.Includes$.<clinit>(Includes.scala)
> [error]     at scalafx.stage.Stage.title(Stage.scala:107)
> [error]     at scalafx.stage.Stage.title_$eq(Stage.scala:109)
> [error]     at hello.ScalaFXHelloWorld$$anon$4.<init>(ScalaFXHelloWorld.scala:43)
> [error]     at hello.ScalaFXHelloWorld$.delayedEndpoint$hello$ScalaFXHelloWorld$1(ScalaFXHelloWorld.scala:42)
> [error]     at hello.ScalaFXHelloWorld$delayedInit$body.apply(ScalaFXHelloWorld.scala:40)
> [error]     at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
> [error]     at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
> [error]     at scalafx.application.JFXApp$$anonfun$init$1.apply(JFXApp.scala:250)
> [error]     at scalafx.application.JFXApp$$anonfun$init$1.apply(JFXApp.scala:250)
> [error]     at scala.collection.immutable.List.foreach(List.scala:381)
> [error]     at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
> [error]     at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:45)
> [error]     at scalafx.application.JFXApp$class.init(JFXApp.scala:250)
> [error]     at hello.ScalaFXHelloWorld$.init(ScalaFXHelloWorld.scala:40)
> [error]     at scalafx.application.AppHelper.start(AppHelper.scala:32)
> [error]     at com.sun.javafx.application.LauncherImpl$8.run(LauncherImpl.java:837)
> [error]     at com.sun.javafx.application.PlatformImpl$7.run(PlatformImpl.java:335)
> [error]     at com.sun.javafx.application.PlatformImpl$6$1.run(PlatformImpl.java:301)
> [error]     at com.sun.javafx.application.PlatformImpl$6$1.run(PlatformImpl.java:298)
> [error]     at java.security.AccessController.doPrivileged(Native Method)
> [error]     at com.sun.javafx.application.PlatformImpl$6.run(PlatformImpl.java:298)
> [error]     at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
> [error] Caused by: java.lang.ClassNotFoundException: javafx.scene.chart.LineChart$SortingPolicy
> [error]     at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
> [error]     at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
> [error]     at java.security.AccessController.doPrivileged(Native Method)
> [error]     at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
> [error]     at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> [error]     at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
> [error]     at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> [error]     ... 24 more
> ```

**Comment by jpsacha** [comment]
Are you using Java 8 u40 or newer? The missing class was introduced in u40.

**Comment by phdoerfler** [comment]
Nope, now I am! Thanks :) You think u40 should be mentioned in the requirements? Pretty sure there are others out there running even older versions.

**Comment by jpsacha** [comment]
Added note to README.md.
