### ISSUE TITLE
License

### ISSUE THREAD

**Issue by akauppi** [scalafx/scalafx-hello-world#3]
About https://github.com/scalafx/scalafx-hello-world/blob/master/LICENSE

The current license seems copied from ScalaFX project itself. Since this one is a template, intended to get people started using ScalaFX I would ask you to consider ~~something like the MIT license, or~~ simply putting the code in public domain. I believe this also is the actual intention by having such a template available.

**Comment by jpsacha** [comment]
Yes, the license is the same as for ScalaFX. It is BSD open source license, very similar to MIT. Why do you think MIT would be a better choice? It is almost exactly the same as BSD used here?

**Comment by akauppi** [comment]
You are right, @jpsacha 

What I see as a problem is needing to mark anything built on this template as "Copyright (c) 2014, ScalaFX", forever. That's hardly the intention. So rephrasing my thoughts to say that this kind of template is best put in the public domain, I think.

**Comment by jpsacha** [comment]
Using [Unlicence](http://unlicense.org/) or [CC-0](http://choosealicense.com/licenses/cc0/) (though that one is very long) may be useful for a demo code. See also discussion of possible issues if [no license](http://choosealicense.com/no-license/) is used.
